version: "3.9"

volumes:
  pgdata:


services:
  db:
    build:
      context: ./db
    environment:
      POSTGRES_DB: geo_heatmap_db
      POSTGRES_USER: geo_heatmap_user
      POSTGRES_PASSWORD: G30_H34TmAp_4pp!
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - geo_heatmap_network

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    command: sh -c "sleep 30 && python3 app/process_data.py && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    networks:
      - geo_heatmap_network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    command: sh -c "npm run build && npm install -g serve; serve -s build"
    networks:
      - geo_heatmap_network

networks:
  geo_heatmap_network:
    driver: bridge
